name: unified-supply-chain-dp
version: v1alpha
type: lens
tags:
  - Tier.Generated
  - SemanticModelAgent
description: |
  The unified Supply Chain data product provides stakeholders with a comprehensive view of inventory, warehouses, orders, and shipments, enabling more informed decision-making regarding logistics and resource allocation. By integrating geolocation data for both origins and destinations, this product enhances lead-time analysis, allowing businesses to optimize delivery routes and improve customer satisfaction. This holistic perspective supports strategic planning and operational efficiency across the supply chain, driving better performance and cost savings.
workspace: public
lens:
  compute: runnable-default
  secrets:
    - name: githubrepo
      allKeys: true
  source:
    type: minerva
    name: minervac
    catalog: icebase
  repo:
    url: https://github.com/sunnysnowflake02-cell/dp-builder-20260526
    lensBaseDir: model
    syncFlags:
      - --ref=main
  api:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  router:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  worker:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  metric:
    logLevel: info
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi
