name: us-nrc-test-dp
version: v1alpha
type: lens
tags:
  - Tier.Generated
  - SemanticModelAgent
description: |
  This deployment manifest provides stakeholders with a comprehensive view of nuclear safety and facility intelligence, integrating various reactor data, risk profiles, and inspection histories into a centralized system. By transitioning to an automated Nuclear Regulatory Control Tower, organizations can enhance their ability to track risk exposure, standardize public data, and make informed, timely decisions regarding safety. This lens is essential for regulatory bodies, facility managers, and safety analysts, as it supports proactive monitoring and improves overall safety management in the nuclear sector.
layer: user
owner: manpreetsingh
workspace: public
lens:
  compute: runnable-default
  secrets:
    - name: githubrepo
      allKeys: true
  source:
    type: minerva
    name: minervac
    catalog: icebase
  repo:
    url: https://github.com/sunnysnowflake02-cell/dp-builder-20260526
    lensBaseDir: dp-builder-20260526/model
    syncFlags:
      - --ref=dataos-dev
  api:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  router:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  worker:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  metric:
    logLevel: info
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi
