name: customer-360-segmentation-usecase
version: v1alpha
type: lens
tags:
  - Tier.Generated
  - SemanticModelAgent
description: |
  The Customer 360 Segmentation lens provides stakeholders with a comprehensive view of customer demographics, purchase behaviors, brand preferences, and channel engagement specifically for the Mars snacking business unit. This semantic view enables effective segmentation of enterprise and retail customers, allowing for targeted marketing strategies and improved customer engagement. By adhering to governance policies that protect sensitive information, decision-makers can confidently analyze customer data while ensuring compliance and privacy. This lens is essential for driving data-informed decisions that enhance customer relationships and optimize marketing efforts.
layer: user
owner: manpreetsingh
workspace: public
lens:
  compute: runnable-default
  secrets:
    - name: githubrepo
      allKeys: true
  source:
    type: minerva
    name: minervac
    catalog: icebase
  repo:
    url: https://github.com/sunnysnowflake02-cell/dp-builder-20260526
    lensBaseDir: dp-builder-20260526/model
    syncFlags:
      - --ref=dataos-dev
  api:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  router:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  worker:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  metric:
    logLevel: info
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi
