name: us-nrc-test-dp
version: v1alpha
type: lens
tags:
  - Tier.Generated
  - SemanticModelAgent
description: |
  This deployment manifest provides a comprehensive view of enterprise laptop fleets, focusing on critical dimensions such as customer context, device performance, and network connectivity. Stakeholders will gain insights into device health, early warning signals for potential failures, and overall fleet stability, enabling informed decisions on resource allocation and remediation priorities. By emphasizing key performance indicators related to device telemetry and service analytics, this product supports proactive management of device issues while ensuring sensitive information is appropriately protected.
layer: user
owner: manpreetsingh
workspace: public
lens:
  compute: runnable-default
  secrets:
    - name: githubrepo
      allKeys: true
  source:
    type: minerva
    name: minervac
    catalog: icebase
  repo:
    url: https://github.com/sunnysnowflake02-cell/dp-builder-20260526
    lensBaseDir: dp-builder-20260526/model
    syncFlags:
      - --ref=dataos-dev
  api:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  router:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  worker:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  metric:
    logLevel: info
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi
